name: Internship Bot Daily Run

on:
  schedule:
    - cron: '0 12 * * *'  # runs daily at 12:00 UTC (adjust if needed)
  workflow_dispatch:      # allows manual trigger from GitHub UI

permissions:
  contents: write
  
jobs:
  run-internship-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run internship bot
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python bot.py

      - name: Commit changes (posted job history)
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add pastJobs.txt
          git diff --cached --quiet || git commit -m "Update posted job list"
          git push
